In [39]:
import numpy as np

In [40]:
#Función para suma de matrices
def Sum(a,b):
    matrix1=np.zeros((a,b))
    matrix2=np.zeros((a,b))
    matrix3=np.zeros((a,b))
    #Rellenando primera matriz
    print("\nPrimera matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix1[i][j]=x
    #Rellenando segunda matriz
    print("\nSegunda matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix2[i][j]=x
    #Suma de matrices
    print("\nMatriz resultante: ")
    for i in range(a):
        for j in range(b):
            matrix3[i][j]=matrix1[i][j]+matrix2[i][j]
    return matrix3
#Función para resta de matrices
def Res(a,b):
    matrix1=np.zeros((a,b))
    matrix2=np.zeros((a,b))
    matrix3=np.zeros((a,b))
    #Rellenando primera matriz
    print("\nPrimera matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix1[i][j]=x
    #Rellenando segunda matriz
    print("\nSegunda matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix2[i][j]=x
    #Suma de matrices
    print("\nMatriz resultante: ")
    for i in range(a):
        for j in range(b):
            matrix3[i][j]=matrix1[i][j]-matrix2[i][j]
    return matrix3
#Función para multiplicación de matrices
def Mult(a,b):
    matrix1=np.zeros((a,b))
    matrix2=np.zeros((a,b))
    matrix3=np.zeros((a,b))
    #Rellenando primera matriz
    print("\nPrimera matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix1[i][j]=x
    #Rellenando segunda matriz
    print("\nSegunda matriz: ")
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix2[i][j]=x
    #Multiplicación de matrices
    print("\nMatriz resultante: ")
    for i in range(a):
        for j in range(b):
            for k in range(a):
                 matrix3[i][j]=matrix3[i][j]+matrix1[i][k]*matrix2[k][j]
    return matrix3
#Determinante matrix 2x2
def Detr(a,b):
    matrix1=np.zeros((a,b))
    f1=1
    f2=1
    determinante=0
    for i in range(a):
        for j in range(b):
            x=float(input("Ingresa un valor: "))
            matrix1[i][j]=x
    for i in range(a):
        for j in range(b):
            if(i==j):
                f1=f1*matrix1[i][j]
            else:
                f2=f2*matrix1[i][j]
    determinante=f1-f2
    return determinante

In [41]:
#Here you have a code for Matrix Algebra
a=int(input("Ingrese el número de columnas: "))
b=int(input("Ingrese el número de renglones: "))
print(Sum(a,b))
print(Res(a,b))
print(Mult(a,b))
print(Detr(a,b))

Ingrese el número de columnas: 2
Ingrese el número de renglones: 2

Primera matriz: 
Ingresa un valor: 1
Ingresa un valor: 2
Ingresa un valor: 3
Ingresa un valor: 4

Segunda matriz: 
Ingresa un valor: 5
Ingresa un valor: 6
Ingresa un valor: 7
Ingresa un valor: 8

Matriz resultante: 
[[ 6.  8.]
 [10. 12.]]

Primera matriz: 
Ingresa un valor: 1
Ingresa un valor: 2
Ingresa un valor: 3
Ingresa un valor: 4

Segunda matriz: 
Ingresa un valor: 5
Ingresa un valor: 6
Ingresa un valor: 7
Ingresa un valor: 8

Matriz resultante: 
[[-4. -4.]
 [-4. -4.]]

Primera matriz: 
Ingresa un valor: 1
Ingresa un valor: 2
Ingresa un valor: 3
Ingresa un valor: 4

Segunda matriz: 
Ingresa un valor: 5
Ingresa un valor: 6
Ingresa un valor: 7
Ingresa un valor: 8

Matriz resultante: 
[[19. 22.]
 [43. 50.]]
Ingresa un valor: 1
Ingresa un valor: 2
Ingresa un valor: 3
Ingresa un valor: 4
-2.0
